### ISSUE TITLE
Can you post the skeleton codes?

### ISSUE THREAD

**Issue by Pezhin** [victorzhao1990/15213-ICS-Fall15#1]
I am looking for the skeleton codes but I can only find the first lab on the website of 15-213 as I am not a student of CMU.

Can you please post the skeleton codes as well or can you send me a copy of that via email?

**Comment by victorzhao1990** [comment]
You can just refer to this page. http://csapp.cs.cmu.edu/3e/labs.html

**Comment by Pezhin** [comment]
Thanks a lot.
